apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: neo4j-kv
  namespace: neo4j
spec:
  provider: azure
  parameters: 
    keyvaultName: zaingpt-kv-dev
    tenantId: e04a8448-b3ff-47bf-8939-88810f47fa
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "6f7cd2ab-9f89-4949-9311-b4ecee06905f"
   
    objects: |
      array:
        - |
          objectName: neo4j-password
          objectType: secret

  secretObjects:
    - secretName: neo4j-auth
      type: Opaque
      data:
        - objectName: neo4j-password
          key: NEO4J_AUTH
