apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: openwebui-kv
  namespace: openwebui
spec:
  provider: azure
  parameters:
    keyvaultName: zaingpt-kv-dev
    tenantId: e04a8448-b3ff-47bf-8939-88810f47fa
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "6f7cd2ab-9f89-4949-9311-b4ecee06905f"
    objects: |
      array:
        - |
          objectName: webui-secret-key
          objectType: secret
        - |
          objectName: openai-api-base-url
          objectType: secret
        - |
          objectName: openai-api-key
          objectType: secret
        - |
          objectName: openwebui-database-url
          objectType: secret

  secretObjects:
    - secretName: openwebui-kv-sync
      type: Opaque
      data:
        - objectName: webui-secret-key
          key: webui-secret-key
        - objectName: openai-api-base-url
          key: openai-api-base-url
        - objectName: openai-api-key
          key: openai-api-key
        - objectName: openwebui-database-url
          key: openwebui-database-url
