apiVersion: v1
kind: Service
metadata:
  name: open-webui-service
  namespace: openwebui
spec:
  type: ClusterIP
  ports:
    - port: 80         # The port you will type in your browser
      targetPort: 8080 # The internal port Open WebUI is listening on
      protocol: TCP
  selector:
    app: open-webui    # Must match your Deployment's labels
