apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: better-rag
  labels:
    app: better-rag
    component: api
spec:
  selector:
    app: better-rag
    component: api
  ports:
    - port: 8000
      targetPort: 8000
      name: http
      protocol: TCP
  type: ClusterIP
