apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  interval: 30m
  chart:
    spec:
      chart: keda
      version: "2.14.*"
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: flux-system
  values:
    replicaCount: 2
    nodeSelector:
      workload: app
    resources:
      operator:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
      metricServer:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    prometheus:
      metricServer:
        enabled: true
        serviceMonitor:
          enabled: true
      operator:
        enabled: true
        serviceMonitor:
          enabled: true
